steps:
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install node_modules based on package.json'
    args: ['install']
  # NOTE: npx is used as workaround to allow serverless command to be found
  # https://github.com/serverless/serverless/issues/4889
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install npx'
    args: ['install', '-g', 'npx']
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install Serverless framework using npm'
    args: ['install', '-g', 'serverless@1.61.0']
  - name: gcr.io/cloud-builders/gcloud
    id: 'Decrypt credentials using KMS'
    args:
      - kms
      - decrypt
      - --ciphertext-file=keyfile.json.enc
      - --plaintext-file=keyfile.json
      - --location=global
      - --keyring=${_KEYRING}
      - --key=${_KEY}
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Deploy serverless framework'
    entrypoint: bash
    args: ['-c', 'npx serverless deploy -v --stage ${_ENV}']
  # - name: gcr.io/cloud-builders/gcloud
  #   id: 'Assign service account to function'
  #   args:
  #     - functions
  #     - deploy
  #     - readRSS
  #     - --service-account=${_SERVICE_ACCOUNT}
substitutions:
  _KEYRING: sls_deploy_account
  _KEY: deploy_creds
  _SERVICE_ACCOUNT: rss-news-service@adventures-in-the-cloud.iam.gserviceaccount.com  