service: news-rss

provider:
  name: google
  stage: dev
  runtime: python37
  region: us-central1
  project: adventures-in-the-cloud
  credentials: /workspace/keyfile.json
  memorySize: 128
  timeout: 10s

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  readRSS:
    handler: readRSS
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: 'projects/${self:provider.project, ""}/topics/one-hour-topic'
    environment:
      SECRET_VERSION: "projects/4700380161/secrets/mongoatlas/versions/latest"